# Generated by Django 6.0.3 on 2026-03-10 12:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "microservice_structure",
                    models.CharField(
                        blank=True,
                        help_text="Structure name for RGWSquared API calls (e.g., 'NFFADI')",
                        max_length=50,
                    ),
                ),
                (
                    "bucket_name_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix for local research bucket names (e.g., 'nffa-di')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("mgmt_access_key", models.CharField(blank=True, max_length=128)),
                ("mgmt_secret_key", models.CharField(blank=True, max_length=128)),
                ("mgmt_keys_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier from identity provider (OAuth2 'sub' claim). This is the PRIMARY KEY for federation. Examples: 'user-123', 'eppn:researcher@university.edu', 'orcid:0000-0002-1825-0097'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "idp_source",
                    models.CharField(
                        db_index=True,
                        default="authentik",
                        help_text="Identity provider that authenticated this user. Examples: 'authentik', 'university-a', 'university-b', 'google'",
                        max_length=100,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Institution affiliation from OAuth2 claims. Examples: 'University A', 'Research Institute B'",
                        max_length=255,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department within institution (e.g., 'Physics', 'Biology')",
                        max_length=255,
                    ),
                ),
                (
                    "affiliation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("faculty", "Faculty"),
                            ("staff", "Staff"),
                            ("student", "Student"),
                            ("affiliate", "Affiliate"),
                            ("guest", "Guest"),
                        ],
                        help_text="User's role/status at institution",
                        max_length=50,
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier for researchers",
                        max_length=19,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "profile_picture_url",
                    models.URLField(
                        blank=True, help_text="URL to user's profile picture from IdP"
                    ),
                ),
                (
                    "last_idp_sync",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time user profile was synced from IdP",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user is approved to access the system",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this user"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address from IdP (OAuth2 'email' claim)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bare S3 bucket name (no tenant prefix)",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name with prefix",
                        max_length=300,
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[("proposal", "Proposal"), ("local", "Local Research")],
                        max_length=10,
                    ),
                ),
                ("is_deletable", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Creator. Null for proposal buckets synced from microservice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_buckets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="storage.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "buckets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BucketPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("ro", "Read-Only"),
                            ("rw", "Read-Write"),
                            ("owner", "Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("microservice", "From Microservice"),
                            ("local", "Local Sharing"),
                        ],
                        default="microservice",
                        max_length=15,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="storage.bucket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bucket_permissions",
            },
        ),
        migrations.CreateModel(
            name="FileUploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_key", models.CharField(max_length=1024)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_records",
                        to="storage.bucket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_upload_records",
            },
        ),
        migrations.CreateModel(
            name="GroupTenantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authentik_group", models.CharField(max_length=200, unique=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_mappings",
                        to="storage.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "group_tenant_mappings",
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ceph_username", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ro", "Read-Only"),
                            ("rw", "Read-Write"),
                            ("admin", "Admin"),
                        ],
                        default="ro",
                        max_length=10,
                    ),
                ),
                (
                    "uo_code",
                    models.CharField(
                        blank=True,
                        help_text="Operational unit code for NFFADI bucket naming (e.g., 'cnr-iom.ts')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("s3_access_key", models.CharField(blank=True, max_length=128)),
                ("s3_secret_key", models.CharField(blank=True, max_length=128)),
                ("credentials_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="storage.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenant_memberships",
            },
        ),
        migrations.CreateModel(
            name="UOMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution_name", models.CharField(max_length=300)),
                ("uo_code", models.CharField(max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uo_mappings",
                        to="storage.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "uo_mappings",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["external_id", "idp_source"], name="users_externa_bc3a56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["institution"], name="users_institu_b16fe1_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bucketpermission",
            unique_together={("bucket", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="fileuploadrecord",
            unique_together={("bucket", "file_key")},
        ),
        migrations.AddIndex(
            model_name="bucket",
            index=models.Index(
                fields=["tenant", "bucket_type"], name="buckets_tenant__f3d606_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bucket",
            unique_together={("name", "tenant")},
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant", "ceph_username"],
                name="tenant_memb_tenant__31f06d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("user", "tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="uomapping",
            unique_together={("tenant", "uo_code")},
        ),
    ]
