# Generated by Django 6.0.3 on 2026-03-13 17:42

from django.db import migrations, models


def populate_display_username(apps, schema_editor):
    """Set display_username for existing users with real emails."""
    User = apps.get_model("storage", "User")
    taken = set()
    for user in (
        User.objects.exclude(email__endswith="@placeholder.local")
        .exclude(email="")
        .order_by("date_joined")
    ):
        if not user.email or "@" not in user.email:
            continue
        base = user.email.split("@")[0].lower()
        candidate = base
        counter = 2
        while candidate in taken:
            candidate = f"{base}-{counter}"
            counter += 1
        taken.add(candidate)
        user.display_username = candidate
        user.save(update_fields=["display_username"])


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_seed_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_username",
            field=models.CharField(
                blank=True,
                help_text="Collision-safe display name derived from email prefix at first login. Used for UI display, sharing, and local bucket naming. Collisions resolved with -2, -3, etc. suffix.",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_display_username, migrations.RunPython.noop),
    ]
