# Generated by Django 6.0.3 on 2026-03-23 21:30
# Modified: merge duplicate users before adding constraint

from django.db import migrations, models


def merge_duplicate_users(apps, schema_editor):
    """Merge duplicate ceph_username entries before adding unique constraint.

    The first-login pipeline bug created duplicate Users when sync-created
    placeholders logged in via Authentik. This merges OAuth data from the
    login-created duplicate into the original sync user and deletes the duplicate.
    """
    TenantMembership = apps.get_model("storage", "TenantMembership")
    User = apps.get_model("storage", "User")
    BucketPermission = apps.get_model("storage", "BucketPermission")

    from django.db.models import Count

    dupes = (
        TenantMembership.objects.filter(is_active=True)
        .values("tenant_id", "ceph_username")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )

    for d in dupes:
        memberships = list(
            TenantMembership.objects.filter(
                tenant_id=d["tenant_id"],
                ceph_username=d["ceph_username"],
                is_active=True,
            ).select_related("user")
        )
        if len(memberships) < 2:
            continue

        # Keeper = sync-created (ms: external_id), Duplicate = login-created
        keeper_m = None
        dupe_m = None
        for m in memberships:
            if m.user.external_id and m.user.external_id.startswith("ms:"):
                keeper_m = m
            else:
                dupe_m = m

        if not keeper_m or not dupe_m:
            sorted_m = sorted(memberships, key=lambda m: m.user.date_joined)
            keeper_m, dupe_m = sorted_m[0], sorted_m[1]

        keeper = keeper_m.user
        dupe = dupe_m.user

        # Collect OAuth data from duplicate before deleting
        new_email = (
            dupe.email
            if (dupe.email and not dupe.email.endswith("@placeholder.local"))
            else None
        )
        new_ext_id = (
            dupe.external_id
            if (dupe.external_id and not dupe.external_id.startswith("ms:"))
            else None
        )
        new_idp = getattr(dupe, "idp_source", "") or ""
        new_first = (
            dupe.first_name if (dupe.first_name and not keeper.first_name) else None
        )
        new_last = dupe.last_name if (dupe.last_name and not keeper.last_name) else None
        new_display = (
            getattr(dupe, "display_username", "")
            if not getattr(keeper, "display_username", "")
            else None
        )
        new_institution = (
            getattr(dupe, "institution", "")
            if not getattr(keeper, "institution", "")
            else None
        )
        new_login = (
            dupe.last_login
            if (
                dupe.last_login
                and (not keeper.last_login or dupe.last_login > keeper.last_login)
            )
            else None
        )

        # Transfer UserSocialAuth BEFORE deleting dupe
        try:
            UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
            UserSocialAuth.objects.filter(user=dupe).update(user=keeper)
        except LookupError:
            pass

        # Delete duplicate first (releases unique email + external_id)
        BucketPermission.objects.filter(user=dupe).delete()
        dupe_m.delete()
        dupe.delete()

        # Now safe to update keeper with released unique values
        if new_email:
            keeper.email = new_email
        if new_ext_id:
            keeper.external_id = new_ext_id
        if new_idp:
            keeper.idp_source = new_idp
        if new_first:
            keeper.first_name = new_first
        if new_last:
            keeper.last_name = new_last
        if new_display:
            keeper.display_username = new_display
        if new_institution:
            keeper.institution = new_institution
        if new_login:
            keeper.last_login = new_login
        keeper.save()

    # Delete orphan users (no membership, not superuser/staff)
    orphans = User.objects.filter(
        memberships__isnull=True,
        is_superuser=False,
        is_staff=False,
    )
    orphans.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_remove_non_nffadi_tenants"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_users, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "ceph_username"),
                name="unique_active_ceph_username_per_tenant",
            ),
        ),
    ]
