# Generated by Django 6.0.3 on 2026-04-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0008_rgwsquared_and_nffadi_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator. Null for proposal buckets synced from RGWSquared.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_buckets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="external_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier from the identity provider (OAuth2 'sub').",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="idp_source",
            field=models.CharField(
                db_index=True,
                default="authentik",
                help_text="Identity provider that authenticated this user.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Institution affiliation from OAuth2 claims.",
                max_length=255,
            ),
        ),
    ]
