apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: storage-system
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOG_LEVEL: "INFO"
  OAUTH_LOG_LEVEL: "DEBUG"

  DATABASE_HOST: "django-postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "djangodb"
  DATABASE_USER: "djangouser"

  S3_ENDPOINT: "REPLACE_WITH_DEV_S3_ENDPOINT"
  S3_USE_SSL: "True"
  S3_VERIFY_SSL: "False"
  S3_REGION: "us-east-1"

  AUTHENTIK_URL: "http://authentik-service:9000"
  AUTHENTIK_EXTERNAL_URL: "http://localhost:9000"
  OIDC_CLIENT_ID: "bucket-manager"

  RGWSQUARED_URL: "REPLACE_WITH_DEV_RGWSQUARED_URL"
